name: quick_news
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  animated_icon: ^0.0.9
  build_runner: ^2.4.12
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.2
  http: any
  intl: ^0.19.0
  json_serializable: ^6.8.0
  relative_time: ^5.0.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.2
  riverpod: ^2.5.1
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
